Explain main functions in readme
makerdao/auction-demo-keeper pull request #21
Opened 2021-03-21 10:11 UTC by Khay-EMMA

2021-03-22 10:08 UTC, pcatana requested changes
I think you should not copy the comments from the files and paste them here. The reader can read them directly from the JS file if they want to understand the functions. 
What I think you should do is make an overview of the main functionality of each module and explain it in a paragraph so the reader gets the bigger picture. If the reader wants to know more, he then goes to the actual file and reads the functions and its comments.

2021-03-22 10:35 UTC, Khay-EMMA commented
> I think you should not copy the comments from the files and paste them here. The reader can read them directly from the JS file if they want to understand the functions.
> What I think you should do is make an overview of the main functionality of each module and explain it in a paragraph so the reader gets the bigger picture. If the reader wants to know more, he then goes to the actual file and reads the functions and its comments.



> I think you should not copy the comments from the files and paste them here. The reader can read them directly from the JS file if they want to understand the functions.
> What I think you should do is make an overview of the main functionality of each module and explain it in a paragraph so the reader gets the bigger picture. If the reader wants to know more, he then goes to the actual file and reads the functions and its comments.

Okay, got that.

2021-03-23 14:48 UTC, pcatana requested changes
Please run through the whole readme and fix any grammar issue and typos. I've seen a couple.

2021-03-23 14:48 UTC, pcatana commented on README.md
> +The Transact module hsndles calculation of gas costs and the signing and sending of transactions. It also has a major class called `GemoetricGasPrice` which is used to get a geometric gas price that
fix typo `hsndles `

2021-03-23 17:13 UTC, pcatana commented
LGTM

2021-03-23 17:14 UTC, merged